[package]
name = "tokio-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
crossbeam = "0.8.4"
futures = "0.3.30"
mini-redis = "0.4.1"
tokio = { version = "1.38.0", features = ["full"] }
